import styled from 'styled-components';
import GrepoBox from './GrepoBox.js';
import Dialog from '@mui/material/Dialog';

export default function GrepoModal({ children, open, onClose }) {
	return (
		<Dialog fullWidth maxWidth='lg' open={open} onClose={onClose}>
			<CloseButton onClick={onClose} />
			<GrepoBox />
			<WindowLeft />
			<WindowRight />
			<WindowTop />
			<WindowBottom />
			<WindowCorner
				style={{
					left: 0,
					height: 17,
					bottom: 0,
					backgroundPosition: 'left 0',
				}}
			/>
			<WindowCorner
				style={{
					right: 0,
					height: 17,
					bottom: 0,
					backgroundPosition: 'right -17px',
				}}
			/>
			<WindowCorner
				style={{
					left: 0,
					height: 44,
					top: 0,
					backgroundPosition: 'left -34px',
				}}
			/>
			<WindowCorner
				style={{
					right: 0,
					height: 44,
					top: 0,
					backgroundPosition: 'right -78px',
				}}
			/>
			<StyledBody>{children}</StyledBody>
		</Dialog>
	);
}

const StyledBody = styled.div`
	background-color: #ffe19b;
	min-height: 400px;
	padding: 40px;
	padding-top: 55px;
	position: relative;
	overflow-x: hidden;
	overflow-y: scroll;
	width: auto;
	font-weight: bold;

	img {
		object-fit: contain;
		width: 100%;
		max-width: 800px;
		margin: 20px auto;
		display: block;
		max-height: 400px;
	}

	p {
		padding: 0 10px;
		margin: 0;
	}

	ol {
		padding: 0 50px;
	}

	h1 {
		text-align: center;
		margin-bottom: 30px;
	}
`;

const WindowLeft = styled.div`
	background-image: url(https://gpit.innogamescdn.com/images/game/layout/vertical_tile.png);
	background-repeat: repeat-y;
	background-position: -10px 0;
	position: absolute;
	top: 44px;
	bottom: 17px;
	width: 16px;
	overflow: hidden;
	display: block;
	left: 0;
	z-index: 2;
`;

const WindowRight = styled.div`
	background-image: url(https://gpit.innogamescdn.com/images/game/layout/vertical_tile.png);
	background-repeat: repeat-y;
	background-position: -26px 0;
	position: absolute;
	top: 44px;
	bottom: 17px;
	width: 16px;
	overflow: hidden;
	display: block;
	right: 0;
	z-index: 2;
`;

const WindowTop = styled.div`
	height: 44px;
	position: absolute;
	left: 16px;
	right: 16px;
	background: url(https://gpit.innogamescdn.com/images/game/layout/gpwindow_horizontal.png) 0 -17px
		repeat-x;
	top: 0;
	z-index: 2;
`;

const WindowBottom = styled.div`
	height: 17px;
	position: absolute;
	left: 16px;
	right: 16px;
	background: url(https://gpit.innogamescdn.com/images/game/layout/gpwindow_horizontal.png) 0 0
		repeat-x;
	bottom: 0;
	z-index: 2;
`;

const WindowCorner = styled.div`
	background-image: url(https://gpit.innogamescdn.com/images/game/layout/gpwindow_corners.png);
	background-repeat: no-repeat;
	width: 16px;
	position: absolute;
	z-index: 2;
`;

const CloseButton = styled.button`
	float: right;
	padding: 0;
	border: none;
	cursor: pointer;
	background: url(https://gpit.innogamescdn.com/images/game/autogenerated/windows/buttons/buttons_54e0a71.png)
		no-repeat 0 -40px;
	width: 50px;
	height: 20px;
	z-index: 10;
	position: absolute;
	right: 7px;
	top: 7px;
	z-index: 3;
`;
