import styled from 'styled-components';

const ColorMap = {
	red: '0 -80px',
	yellow: '-150px -40px',
	blue: '0 0px',
};

export default function GrepoButton({ color, children, href }) {
	return (
		<>
			<ButtonDiv
				style={{
					backgroundPosition: ColorMap[color],
				}}
			>
				<ButtonLink href={href} target='_blank'>
					{children}
				</ButtonLink>
			</ButtonDiv>
		</>
	);
}

const ButtonDiv = styled.div`
	background: url('https://it0.grepolis.com/images/game/autogenerated/master_page/master_page_10440d0.png')
		no-repeat;
	width: 150px;
	height: 40px;
`;

const ButtonLink = styled.a`
	display: block;
	height: 100%;
	color: #fff;
	width: 100%;
	height: 40px;
	text-align: center;
	line-height: 40px;
	cursor: pointer;
	font-weight: bold;
	text-decoration: none;

	&:hover {
		color: #fff;
		font-weight: bold;
		text-decoration: none;
	}
`;
